# ORDER MATTERS HERE BECAUSE OF YQ PARSER!
apiVersion: v1
kind: Secret
metadata:
  name: kubevirt-provider-credentials
  namespace: garden-dev
type: Opaque
data:
  kubeconfig: << KUBECONFIG SHOOT >>
---
apiVersion: core.gardener.cloud/v1beta1
kind: SecretBinding
metadata:
  name: kubevirt-provider-credentials
  namespace: garden-dev
secretRef:
  name: kubevirt-provider-credentials
quotas: []
---
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: kubevirt-1
  namespace: garden-dev
spec:
  secretBindingName: kubevirt-provider-credentials
  cloudProfileName: local
  region: local
  purpose: development
  provider:
    type: kubevirt
    infrastructureConfig:
      # namespace where VMs are going to be created
      namespace: "default"
    controlPlaneConfig:
      foo: bar
    workers:
    - name: cpu-worker
      minimum: 3
      maximum: 5
      providerConfig:
        namespace: default
      machine:
        type: local
        image:
          name: "ubuntu"
          version: "16.04"
  kubernetes:
    version: 1.17.5
  networking:
    type: calico
    pods: 100.96.0.0/11
    nodes: 10.250.0.0/16
    services: 100.64.0.0/13
    providerConfig:
      apiVersion: calico.networking.extensions.gardener.cloud/v1alpha1
      kind: NetworkConfig
      backend: bird
      ipam:
        type: host-local
        cidr: usePodCIDR
  addons:
    nginxIngress:
      enabled: false
    kubernetesDashboard:
      enabled: false
